### PR TITLE
Update to 7.3

### PR DESCRIPTION
**Pull request by justinush**
Updated to version 7.3

### CODE REVIEW

**Comment by thamaraiselvam** [comment]
@justinushermawan  I really appreciate you for the PR.

Did you run the script and made sure that it is working?

**Comment by thamaraiselvam** [comment]
I ran the script it's failing because of PPA is missing

Error:

`E: Unable to locate package php7.3-fpm`


Possible fix 

Add the following lines before installing php

```
sudo add-apt-repository ppa:ondrej/php -y
sudo apt-get update
```

also should change the version in nginx configuration file

https://github.com/thamaraiselvam/LEMP-Installer/blob/93031617ed5079c13dd4d0aabb49a439d8c652e0/default#L15

**Comment by justinush** [comment]
@thamaraiselvam Hey, thank you for the correction. Just tested successfully on Ubuntu 18.04 and pushed a new commit for the fixing.

**Comment by thamaraiselvam** [comment]
Congratulations @justinushermawan 
Your first PR is merged  🎉🎉

**Comment by justinush** [comment]
Thank you, @thamaraiselvam!

**Pull request merged**
